name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=8192"

jobs:
  astrocheck:
    name: Check for type issues with astro check
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/setup

      - name: Run Check
        run: pnpm run check
  
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/setup

      - name: Run Prettier
      - run: pnpm format:check